#! /usr/bin/env zsh

dir=$(dirname "${0:a:h}")/models

# call model-to-stla-x for all folders
models=(${dir}/*(/N))
for model in ${models}; do
  echo "model: ${model}"
  ./scripts/model-to-stla-x "${model}"
done
